# app metadata
app: "orcal-helloworld-service"

# resource requests and limits
resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 400m
    memory: 800Mi

ingresses:

serviceAnnotations:
# allow consul-sync-catalog to register this service
- key: consul.hashicorp.com/service-port
  value: "8080"
- key: consul.hashicorp.com/service-sync
  value: "true"

envSecrets:
- variable: MONGODB_PASSWORD
  secretName: connections
  secretKey: mongodb-password
- variable: MYSQL_PASSWORD
  secretName: connections
  secretKey: mysql-password
